### ISSUE TITLE
When autostart is true, setting voice does not work.

### ISSUE THREAD

**Issue by AndrewKeig** [AndrewKeig/react-speech#3]

**Comment by AndrewKeig** [comment]
I think all properties bar speech and style have this isssue.

**Comment by thevaleriemack** [comment]
+1

solutions?

**Comment by toxic-johann** [comment]
Can this package solve this problem? https://www.npmjs.com/package/enable-auto-tts

**Comment by AndrewKeig** [comment]
hey, I think at some point in the past this was a feature, but various browsers stopped supporting it, so it was removed:

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by toxic-johann** [comment]
Sounds good, although I met this aging on my iOS. But I feel it's ok that in the most situations we don't need this.
